stages:
  Data_Ingestion:
    cmd: python src\pneumonia_detection\pipeline\stage_1.py
    deps:
      - src\pneumonia_detection\pipeline\stage_1.py
      - config\config.yaml
      - params.yaml
    outs:
      - artifacts/data_ingestion
  
  Prepare_Base_Model:
    cmd: python src\pneumonia_detection\pipeline\stage_2.py
    deps:
      - src\pneumonia_detection\pipeline\stage_2.py
      - config\config.yaml
      - params.yaml
    outs:
      - artifacts/prepare_base_model

  Model_Training:
    cmd: python src\pneumonia_detection\pipeline\stage_3.py 
    deps:
      - src\pneumonia_detection\pipeline\stage_3.py
      - artifacts\data_ingestion\chest_xray\train
      - artifacts\data_ingestion\chest_xray\val
      - artifacts\prepare_base_model\updated_base_model.h5
      - artifacts\data_ingestion\chest_xray\test
      - config\config.yaml
      - params.yaml
    outs:
      - artifacts/training
      - models/model.h5

  Model_Evaluation:
    cmd: python src\pneumonia_detection\pipeline\stage_4.py
    deps:
      - src\pneumonia_detection\pipeline\stage_4.py
      - artifacts\data_ingestion\chest_xray\val
      - models\model.h5
      - config\config.yaml
      - params.yaml
    metrics:
      - scores.json:
        cache: false
