artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: research/chest-xray-pneumonia.zip
  unzip_dir: artifacts/data_ingestion/pneumonia

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5 

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/prepare_base_model/updated_base_model.h5
  production_model_path: models/model.h5
  training_data: artifacts/data_ingestion/pneumonia/chest_xray/train
  test_data: artifacts/data_ingestion/pneumonia/chest_xray/test
  val_data: artifacts/data_ingestion/pneumonia/chest_xray/val

evaluation:
  path_of_model: models/model.h5
  val_data: artifacts/data_ingestion/pneumonia/chest_xray/val
  test_data: artifacts/data_ingestion/pneumonia/chest_xray/test
  training_data: artifacts/data_ingestion/pneumonia/chest_xray/train
  evaluation_metrics: artifacts/evaluation/metrics.json
  mlflow_uri: https://dagshub.com/Aldoreni45/pneumonia_detection_mlops.mlflow/
  